#pragma once

#ifndef MGMAKE_MGMAKE_HXX
#define MGMAKE_MGMAKE_HXX

#include "detail/static_string.hxx"
#include "detail/enum.hxx"
#include "detail/enum_flag.hxx"
#include "detail/enum_string.hxx"
#include "detail/convert.hxx"
#include "detail/assert.hxx"
#include "detail/graphviz.hxx"
#include "detail/hashes.hxx"
#include "sys/platform.hxx"
#include "sys/util.hxx"
#include "sys/command_line.hxx"
#include "sys/file_command.hxx"
#include "discovery/tool_role.hxx"
#include "discovery/tool_provider.hxx"
#include "discovery/mode.hxx"
#include "discovery/tool_family.hxx"
#include "discovery/tool_binding.hxx"
#include "discovery/resolved_tool.hxx"
#include "discovery/tool_environment.hxx"
#include "discovery/resolved_toolchain.hxx"
#include "discovery/source_role.hxx"
// Include json extension here
// Needs to be included earlier bc it's used in the cmake extension
// but if it is included first by the cmake extension, the cmake ext.
// will need to be enabled for json. But json is used for other features
// as well, and as such should be available independently of the cmake ext.
#include "ext/json.hxx"
#include "dep/format.hxx"
#include "dep/file.hxx"
#include "dep/parser.hxx"
#include "dep/database.hxx"
#include "build/toolchain.hxx"
#include "build/toolchain_registry.hxx"
#include "build/request.hxx"
#include "build/request_from_options.hxx"
#include "build/artifact_names.hxx"
#include "build/target.hxx"
#include "build/clean.hxx"
#include "build/run.hxx"
#include "cli/action.hxx"
#include "cli/backend.hxx"
#include "cli/options.hxx"
#include "cli/help.hxx"
#include "cli/parse_result.hxx"
#include "cli/option_parse_result.hxx"
#include "cli/value_parser.hxx"
#include "cli/enum_value_parser.hxx"
#include "cli/option_builder.hxx"
#include "cli/option_parser.hxx"
#include "cli/parse.hxx"
#include "cli/util.hxx"
#include "dag/action.hxx"
#include "dag/artifact.hxx"
#include "dag/graph.hxx"
#include "dag/target.hxx"
#include "dag/emitter.hxx"
#include "dag/execute.hxx"
#include "backend/ninja.hxx"
#include "backend/registry.hxx"
#include "backend/capabilities.hxx"
#include "backend/execute.hxx"
// Include extensions before specs that reference provider/fetch types.
#include "ext/provider_kind.hxx"
#include "ext/path_root.hxx"
#include "ext/provided_target_ref.hxx"
#include "ext/rooted_path.hxx"
#include "ext/fetch.hxx"
#ifdef MGMK_ENABLE_EXT_CMAKE
#include "ext/cmake/project.hxx"
#include "ext/cmake/target.hxx"
#include "ext/cmake/codemodel.hxx"
#include "ext/cmake/file_api.hxx"
#endif // MGMK_ENABLE_EXT_CMAKE
#include "spec/executable.hxx"
#include "spec/executable_impl.hxx"
#include "spec/library.hxx"
#include "spec/library_impl.hxx"
#include "acquire/fetched.hxx"
#include "acquire/result.hxx"
#include "acquire/context.hxx"
#include "acquire/context_impl.hxx"
#include "acquire/plan.hxx"
#include "configure/result.hxx"
#include "configure/context.hxx"
#include "configure/context_impl.hxx"
#ifdef MGMK_ENABLE_EXT_CMAKE
#include "configure/cmake/project.hxx"
#include "configure/cmake/paths.hxx"
#include "configure/cmake/command.hxx"
#endif // MGMK_ENABLE_EXT_CMAKE
#include "configure/plan.hxx"
#ifdef MGMK_ENABLE_EXT_CMAKE
#include "prep/cmake/project.hxx"
#include "prep/cmake/finalize.hxx"
#endif // MGMK_ENABLE_EXT_CMAKE
#include "prep/result.hxx"
#include "prep/finalize.hxx"
#include "spec/project.hxx"
#include "discovery/discovery.hxx"
#include "lower/target.hxx"
#include "lower/usage.hxx"
#ifdef MGMK_ENABLE_EXT_CMAKE
#include "lower/provider_build.hxx"
#endif // MGMK_ENABLE_EXT_CMAKE
#include "lower/context.hxx"
#include "lower/objects.hxx"
#ifdef MGMK_ENABLE_EXT_CMAKE
#include "lower/cmake/provider.hxx"
#endif // MGMK_ENABLE_EXT_CMAKE
#include "lower/context_impl.hxx"
#include "lower/project.hxx"
#include "lower/project_impl.hxx"
#include "spec/project_impl.hxx"
#include "detail/project_factory.hxx"
#include "entry/exit_code.hxx"
#include "entry/entry.hxx"
#include "entry/macro.hxx"

#endif // MGMAKE_MGMAKE_HXX
