#pragma once

#ifndef MGMAKE_DAG_ARTIFACT_HXX
#define MGMAKE_DAG_ARTIFACT_HXX

#include "../detail/hashes.hxx"

#include <filesystem>
#include <system_error>
#include <vector>

// A DAG artifact is a node: source, discovered header, generated file, or phony target placeholder.

namespace mgmake::dag {
    struct artifact {
        using id = std::vector<artifact>::size_type;

        enum struct kind {
            source, // A source code (.cxx, .c, etc)
            header, // Header/source dependency discovered from compiler dependency info
            system, // Provided by the system
            generated, // Generated by another program
            phony // Fake placeholder
        } m_kind = kind::source;
        std::filesystem::path m_path;

        [[nodiscard]] inline const std::filesystem::path& path() const noexcept {
            return m_path;
        }

        [[nodiscard]] inline bool is_phony() const noexcept {
            return m_kind == kind::phony;
        }
        [[nodiscard]] inline bool is_system() const noexcept {
            return m_kind == kind::system;
        }

        [[nodiscard]] inline bool exists() const {
            if (is_phony()) {
                return true;
            }

            std::error_code ec;
            return std::filesystem::exists(m_path, ec);
        }

        [[nodiscard]] inline bool is_regular_file() const {
            if (is_phony()) {
                return false;
            }

            std::error_code ec;
            return std::filesystem::is_regular_file(m_path, ec);
        }

        [[nodiscard]] inline bool is_dirty(const detail::hashes& hashes) const {
            if (is_phony()) {
                return false;
            }

            if (!exists()) {
                return true;
            }

            if (!is_regular_file()) {
                return false;
            }

            return hashes.is_dirty(m_path);
        }

        [[nodiscard]] inline bool check(detail::hashes& hashes) const {
            if (is_phony()) {
                return false;
            }

            if (!exists()) {
                return true;
            }

            if (!is_regular_file()) {
                return false;
            }

            return hashes.check(m_path);
        }

        inline void update(detail::hashes& hashes) const {
            if (is_phony()) {
                return;
            }

            hashes.update(m_path);
        }
    };
}

#endif // MGMAKE_DAG_ARTIFACT_HXX