#pragma once

#ifndef MGMAKE_BACKEND_NINJA_HXX
#define MGMAKE_BACKEND_NINJA_HXX

#include "../build/request.hxx"
#include "../cli/options.hxx"
#include "../dag/graph.hxx"
#include "../discovery/resolve.hxx"
#include "../sys/util.hxx"

#include <cstdlib>
#include <expected>
#include <filesystem>
#include <fstream>
#include <ranges>
#include <set>
#include <string>
#include <string_view>
#include <utility>

// The Ninja backend serializes mgmake actions into build.ninja rules, then invokes the resolved ninja executable.

namespace mgmake::backend {
    namespace detail {
        inline std::string ninja_escape_build_text(std::string_view text) {
            std::string result;

            for (const char ch : text) {
                switch (ch) {
                    case '$':
                        result += "$$";
                        break;

                    case ' ':
                        result += "$ ";
                        break;

                    case ':':
                        result += "$:";
                        break;

                    case '|':
                        result += "$|";
                        break;

                    case '\n':
                        result += "$\n";
                        break;

                    default:
                        result += ch;
                        break;
                }
            }

            return result;
        }

        inline std::string ninja_escape_path(const std::filesystem::path& path) {
            return ninja_escape_build_text(path.generic_string());
        }

        inline std::string ninja_escape_variable_text(std::string_view text) {
            std::string result;

            for (const char ch : text) {
                switch (ch) {
                    case '$':
                        result += "$$";
                        break;

                    case '\n':
                        result += "$\n";
                        break;

                    default:
                        result += ch;
                        break;
                }
            }

            return result;
        }

        inline void write_artifact_list(std::ofstream& out, const dag::graph& graph, const std::vector<dag::artifact::id>& artifacts) {
            bool first = true;

            for (const auto id : artifacts) {
                const auto& artifact = graph.artifact(id);

                if (!first) {
                    out << ' ';
                }

                out << ninja_escape_path(artifact.m_path);
                first = false;
            }
        }
		inline void write_artifact_list(std::ofstream& out, const dag::graph& graph, const std::set<dag::artifact::id>& artifacts) {
			return write_artifact_list(out, graph, artifacts | std::ranges::to<std::vector<dag::artifact::id>>());
		}

        inline void create_output_directories(const dag::graph& graph) {
            for (const auto& action : graph.m_actions) {
                for (const auto output_id : action.m_outputs) {
                    const auto& output = graph.artifact(output_id);

                    if (output.m_kind == dag::artifact::kind::phony) {
                        continue;
                    }

                    const auto parent = output.m_path.parent_path();

                    if (!parent.empty()) {
                        std::filesystem::create_directories(parent);
                    }
                }
            }
        }

        inline void write_target_defaults(std::ofstream& out, const dag::graph& graph) {
            if (graph.m_targets.empty()) {
                return;
            }

            out << "\ndefault";

            for (const auto& target : graph.m_targets) {
                out << ' ' << ninja_escape_build_text(target.m_name);
            }

            out << "\n";
        }
    }

    struct ninja {
        std::filesystem::path m_output_file = "build.ninja";

        void generate(const cli::options&, const dag::graph& graph, const build::request& req) const {
            auto output_path = req.build_dir() / m_output_file;
            if (output_path.has_parent_path()) {
                std::filesystem::create_directories(output_path.parent_path());
            }
            detail::create_output_directories(graph);

            std::ofstream out(output_path);
			mgmkassert(out.is_open(), "ninja backend: failed to open " + output_path.string());

            out << "# generated by mgmake\n\n";

            out << "builddir = "
                << detail::ninja_escape_variable_text(req.build_dir().generic_string())
                << "\n\n";

            bool needs_always = false;

            for (const auto& action : graph.m_actions) {
                if (action.m_always_run) {
                    needs_always = true;
                    break;
                }
            }

            if (needs_always) {
                out << "build __mgmake_always: phony\n\n";
            }

            // Each mgmake action becomes one Ninja rule/build pair so commands can stay action-local.
            for (auto i = 0; i < graph.m_actions.size(); ++i) {
                const auto& action = graph.action(i);

                mgmkassert(not action.m_outputs.empty(), "ninja backend: action '" + action.m_name + "' has no outputs");
                mgmkassert(not action.m_command.m_args.empty(), "ninja backend: action '" + action.m_name + "' has no command");

                out << "rule action_" << i << "\n";
                auto command_text = discovery::wrap_command_for_environment(
                    req.tool_environment(),
                    action.m_command.full_command()
                );
                out << "  command = " << command_text << "\n";

                if (!action.m_description.empty()) {
                    out << "  description = " << detail::ninja_escape_variable_text(action.m_description) << "\n";
                } else if (!action.m_name.empty()) {
                    out << "  description = " << detail::ninja_escape_variable_text(action.m_name) << "\n";
                }

                if (!action.m_working_directory.empty()) {
#ifdef MGMK_PLATFORM_WINDOWS
                    command_text = "cd /d ";
#else
                    command_text = "cd ";
#endif // MGMK_PLATFORM_WINDOWS
                    command_text += sys::shell_escape(action.m_working_directory.string());
                    command_text += " && ";
                    command_text += action.m_command.full_command();
                    command_text = discovery::wrap_command_for_environment(
                        req.tool_environment(),
                        std::move(command_text)
                    );
                    out << "  command = " << command_text << "\n";
                }

                if (action.m_depfile.has_value()) {
                    const auto& depfile = *action.m_depfile;

                    if (depfile.m_format.has(dep::format_bits::gcc)) {
                        if (!depfile.m_path.empty()) {
                            out << "  depfile = "
                                << detail::ninja_escape_path(depfile.m_path)
                                << "\n";
                        }
                    }

                    if (depfile.m_format.has(dep::format_bits::msvc_show_includes)) {
                        out << "  deps = msvc\n";

                        // This is the default English MSVC /showIncludes prefix.
                        // Localized toolchains may need this to become configurable later.
                        out << "  msvc_deps_prefix = Note: including file:\n";
                    }
                }

                out << "\n";

                out << "build ";
                detail::write_artifact_list(out, graph, action.m_outputs);
                out << ": action_" << i;

                if (!action.m_inputs.empty()) {
                    out << ' ';
                    detail::write_artifact_list(out, graph, action.m_inputs);
                }

                if (action.m_always_run) {
                    out << " | __mgmake_always";
                }

                out << "\n\n";
            }

            // DAG targets become phony Ninja targets that collect outputs and target-level dependencies.
            for (const auto& target : graph.m_targets) {
                // Check if it is a system library
                bool sys_lib = false;
                if (not target.outputs().empty() and target.outputs().size() == 1) {
                    auto& only_artifact = graph.artifact(*target.outputs().begin());
                    if (only_artifact.is_system()) {
                        sys_lib = true;
                    }
                }

                out << "build " << detail::ninja_escape_build_text(target.m_name) << ": phony ";
                if (not target.m_outputs.empty() and not sys_lib) {
                    out << ' ';
                    detail::write_artifact_list(out, graph, target.m_outputs);
                }
                for (const auto dep_id : target.m_dependencies) {
                    const auto& dep = graph.target(dep_id);
                    out << ' ' << detail::ninja_escape_build_text(dep.m_name);
                }
                out << "\n";
            }

            detail::write_target_defaults(out, graph);
        }

		std::expected<void, std::string> build(
            const cli::options& opts,
            const dag::graph& graph,
            const build::request& req
        ) const {
            auto output_path = req.build_dir() / m_output_file;
            if (output_path.has_parent_path()) {
                std::filesystem::create_directories(output_path.parent_path());
            }
			generate(opts, graph, req);

            auto ninja = discovery::resolve_backend_tool(
                opts,
                req,
                discovery::backend_tool_requirement{
                    .m_role = discovery::tool_role::generator_ninja,
                    .m_logical_name = opts.m_ninja.empty() ? "ninja" : opts.m_ninja,
                    .m_needed_because = "the selected backend is ninja and this action invokes ninja"
                }
            );

            if (!ninja) {
                return std::unexpected{ninja.error()};
            }

			sys::command_line command;
			command.m_args.emplace_back(ninja->path_string());
			command.m_args.emplace_back("-f");
			command.m_args.emplace_back(output_path.string());

			if (opts.m_dry_run) {
				command.m_args.emplace_back("-n");
			}

			if (opts.m_verbose || opts.m_dry_run) {
				command.m_args.emplace_back("-v");
			}

			// CLI-selected targets are forwarded to Ninja; an empty list lets Ninja build defaults.
			for (const auto& target : req.m_targets) {
				command.m_args.emplace_back(target);
			}

			const auto exit_code = command.invoke({
				.m_verbose = opts.m_verbose || opts.m_dry_run
			});

			if (exit_code != 0) {
				return std::unexpected(
					"ninja backend: ninja failed with exit code " + std::to_string(exit_code)
				);
			}

			return {};
		}
    };
}

#endif // MGMAKE_BACKEND_NINJA_HXX
